export const patternsData = [
    {
        mood: "Feeling Adventurous",
        name: "Sweet Chamomile Socks",
        image: "adventurous.jpg",
        link: "https://www.garnstudio.com/pattern.php?id=11794&cid=19",
        alt: "A pair of handmade lilac socks with a ribbed design, displayed on a person's feet against a white fabric background. The logo 'DROPS DESIGN' and the website 'www.garnstudio.com' are displayed in the corner",
    },
    {
        mood: "Feeling Adventurous",
        name: "Kongletopp",
        image: "adventurous1.jpg",
        link: "https://www.garnstudio.com/pattern.php?id=11368&cid=19",
        alt: "A woman with blonde hair sitting on a wooden bench at a sandy beach, wearing a hand-knitted, dusky pink tank top with a delicate lace pattern. The DROPS DESIGN logo and the website 'www.garnstudio.com' are displayed in the corner.",
    },
    {
        mood: "Calm and Contemplative",
        name: "Unexpected",
        image: "calm.jpg",
        link: "https://www.garnstudio.com/pattern.php?id=9794&cid=19",
        alt: "A smiling woman in black trousers and a long-sleeve top wearing a white hand-knitted vest, standing on concrete stairs. The 'DROPS DESIGN' logo and 'www.garnstudio.com' website are displayed in the corner.",
    },
    {
        mood: "In Need of Comfort",
        name: "Sun and Sand",
        image: "need-comfort.jpg",
        link: "https://www.garnstudio.com/pattern.php?id=7498&cid=19",
        alt: "A joyful woman wearing yellow-colored, hand-knitted blanket in garter stich, standing in a field with tall grasses. The DROPS DESIGN logo and website 'www.garnstudio.com' are present in the corner.",
    },
    {
        mood: "Feeling Festive",
        name: "Bunny Ears Slippers",
        image: "festive.jpg",
        link: "https://www.garnstudio.com/pattern.php?id=11303&cid=19",
        alt: "A person's feet wearing hand-knitted slippers that resemble white bunnies with cute faces, paired with blue denim pants. The image includes the 'DROPS DESIGN' logo and the website 'www.garnstudio.com' in the corner.",
    },
    {
        mood: "Creative and Inspired",
        name: "Mixed Berries Sweater",
        image: "creative-inspired.jpg",
        link: "https://www.garnstudio.com/pattern.php?id=10890&cid=19",
        alt: "A woman with blond hair smiling gently, wearing a fluffy hand-knitted blue sweater with pastel colored stripes and mixed patterns, standing against a bright interior background. The logo 'DROPS DESIGN' with the website 'www.garnstudio.com' is displayed in the corner.",
    },
    {
        mood: "Social Knitter",
        name: "Spa Squares",
        image: "social.jpg",
        link: "https://www.garnstudio.com/pattern.php?id=4933&cid=19",
        alt: "Hand-knitted cosmetic pads in shades of pink and cream are stacked next to a pink bottle labeled 'Make-up Remover by me', all placed on a natural rock surface with grass in the background. The 'DROPS DESIGN' logo and website 'www.garnstudio.com' are visible in the corner.",
    },
    {
        mood: "Short on Time",
        name: "Blushing Ivy Headband",
        image: "time.jpg",
        link: "https://www.garnstudio.com/pattern.php?id=11523&cid=19",
        alt: "A woman in a light cream jacket and grey sweater wearing a hand-knitted pink headband against a natural, blurry lakeside background. The DROPS DESIGN logo and website address 'www.garnstudio.com' are included in the corner.",
    },
    {
        mood: "Eco-Friendly",
        name: "Treasure Hunting",
        image: "eco.jpg",
        link: "https://www.garnstudio.com/pattern.php?id=11231&cid=19",
        alt: "A smiling woman seated on a sandy beach, holding a hand-knitted brown shoulder bag, wearing a white blouse and light blue jeans. The DROPS DESIGN logo and the 'www.garnstudio.com' website are included in the corner.",
    },
]